default_provider = "age"

[providers.age]
type = "age"
recipients = [
    "age1u3ajmcjmgdm3d9x9jeve8k0vxnpddzqyazf4s7hujfmfqv7grffq3t70ta",
    "age1mn90w2du9l9czm9amk503re7ej3n8gy7rfmvq9072fenhrv6hyvqsvmw0h",
]

[secrets]
CONFIG_KEY= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbm1WclAvLzZpU3djMUZvV3gzMFFQd3ZWQzZWdmpkWUJ1bFhIb2tEeFU4CmpyWDRRdFp1NURJY0NSVWs1ZHhod3BzcVRiWVhGL0JKMG5Qd2JCVlpkc2sKLT4gWDI1NTE5IGJKam5EMkpvZks3ZTEyRzdBcGxFNndKRlJjVG5kN3J0NXZqZEwzbVplV00KeDNyVXFVK0d6WkwrZjAwSzNRSHNzRENlM21MZFBsVGo1YWFoV0RrWWpwRQotPiA7I0hhZUEtZ3JlYXNlIFZpb2RbWyMgIj0hClUxQmVHMWwwbnpOQ1BUWVVzd2VZQXRWRmxEN2FEV3NoekZNMksvM2FhS0YzejJQL1Vhd1Y2MjNuaWlZYkhRQjgKQkppQnVoL3NxS3lheHNoT25ZU3pGR3o0MEVzZ1BoRnBCWm1SVXFjVlpQc01kYlMvcEpZCi0tLSBJeGlnNlRCc09QY1dlWCtkeXZkUTNiOHhocVRXVStQVlZrU2ppaDg4VTNFCoS+jeE0jT7x91rOsm93iGqfQmXkZZXPVF73IHCZvfDFSbj2bLyrxdn2SqUPm4h5evvraunhsK5+V7kdoCtaIekAm6Q38hiMW2DWLbVOvq0lUp/FwLBzAhtA4nkYnlS8cUolktPLZWLH4Zw=" }
